services:
  registry:
    container_name: class_registry
    image: registry:2.7
    restart: unless-stopped
    networks:
      - my-net
    ports:
      - "5000:5000"
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: "/certs/domain.crt"
      REGISTRY_HTTP_TLS_KEY: "/certs/domain.key"
      REGISTRY_HTTP_SECRET: "iuehfio73bt8dobq"
    volumes:
     - "./files/config.yml:/etc/docker/registry/config.yml"
     - "./files/htpasswd:/htpasswd"
     - "./data:/var/lib/registry"
     - "./certs:/certs"
  ui:
    container_name: class_registry_ui
    image: joxit/docker-registry-ui:latest
    restart: unless-stopped
    networks:
      - my-net
    ports:
      - "8080:80"
    environment:
      DELETE_IMAGES: "true"
      NGINX_PROXY_PASS_URL: "https://registry:5000"
      REGISTRY_TITLE: "My Private Registry"
      SINGLE_REGISTRY: "true"
    depends_on:
      - registry
networks:
  my-net:
    driver: bridge
