version: 0.1
log:
  accesslog:
    disabled: false
  level: debug
  fields:
    service: registry
    environment: development
storage:
    delete:
      enabled: true
    cache:
      blobdescriptor: inmemory
    filesystem:
      rootdirectory: /var/lib/registry
http:
    addr: 0.0.0.0:5000
    headers:
      X-Content-Type-Options: [nosniff]
      Access-Control-Allow-Origin: ['http://127.0.0.1:8080']
      Access-Control-Allow-Credentials: [true]
      Access-Control-Max-Age: [1728000]
      Access-Control-Allow-Headers: ['Authorization', 'Accept']
      Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
      Access-Control-Expose-Headers: ['Docker-Content-Digest']
auth:
  htpasswd:
    realm: Registry Realm
    path: /htpasswd
notifications:
  endpoints:
    - name: local-8083
      url: http://localhost:8083/callback
      timeout: 1s
      threshold: 10
      backoff: 1s
      disabled: true
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
